/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Ansor150423.view;
import Ansor150423.controller.AnggotaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author acer
 */
   public class FormAnggota extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormAnggota
     */
    AnggotaController anggotaController;
    public FormAnggota() {
        anggotaController = new AnggotaController(this);
        initComponents();
        anggotaController.update_tabel();
    }

    public JComboBox getCboJekel() {
        return cboJekel;
    }

    public void setCboJekel(JComboBox cboJekel) {
        this.cboJekel = cboJekel;
    }

    public JComboBox getCboProdi() {
        return cboProdi;
    }

    public void setCboProdi(JComboBox cboProdi) {
        this.cboProdi = cboProdi;
    }

    public JTextField getTxtNamaAnggota() {
        return txtNamaAnggota;
    }

    public void setTxtNamaAnggota(JTextField txtNamaAnggota) {
        this.txtNamaAnggota = txtNamaAnggota;
    }

    public JTextField getTxtTglLahir() {
        return txtTglLahir;
    }

    public void setTxtTglLahir(JTextField txtTglLahir) {
        this.txtTglLahir = txtTglLahir;
    }

    public JTextField getTxtkodeAnggota() {
        return txtkodeAnggota;
    }

    public void setTxtkodeAnggota(JTextField txtkodeAnggota) {
        this.txtkodeAnggota = txtkodeAnggota;
    }

    public JTable getTabelAnggota() {
        return tabelAnggota;
    }

    public void setTabelAnggota(JTable tabelAnggota) {
        this.tabelAnggota = tabelAnggota;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtkodeAnggota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaAnggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTglLahir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboJekel = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cboProdi = new javax.swing.JComboBox();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();

        setClosable(true);
        setTitle("Anggota");
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 14);
        getContentPane().add(txtkodeAnggota);
        txtkodeAnggota.setBounds(130, 10, 170, 20);

        jLabel2.setText("Nama Anggota");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 110, 14);
        getContentPane().add(txtNamaAnggota);
        txtNamaAnggota.setBounds(130, 40, 250, 20);

        jLabel3.setText("Tanggal lahir");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 110, 14);
        getContentPane().add(txtTglLahir);
        txtTglLahir.setBounds(130, 70, 250, 20);

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 110, 14);

        cboJekel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "L", "P" }));
        getContentPane().add(cboJekel);
        cboJekel.setBounds(130, 100, 80, 20);

        jLabel5.setText("Prodi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 110, 14);

        cboProdi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teknik komputer", "Manajemen Informatika" }));
        getContentPane().add(cboProdi);
        cboProdi.setBounds(130, 130, 250, 20);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(10, 160, 61, 23);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(90, 160, 67, 23);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(170, 160, 63, 23);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(251, 160, 60, 23);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari);
        btnCari.setBounds(300, 10, 80, 23);

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelAnggota);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 192, 370, 200);

        setBounds(0, 0, 405, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        anggotaController.insert_anggota();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        anggotaController.cari_anggota();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        anggotaController.update_anggota();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        anggotaController.delete_anggota();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cboJekel;
    private javax.swing.JComboBox cboProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelAnggota;
    private javax.swing.JTextField txtNamaAnggota;
    private javax.swing.JTextField txtTglLahir;
    private javax.swing.JTextField txtkodeAnggota;
    // End of variables declaration//GEN-END:variables
}