/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Ansor150423.view;
import Ansor150423.controller.PeminjamanController;
import javax.swing.JComboBox;
import javax.swing.JTextField;
/**
 *
 * @author acer
 */
   public class FormPeminjaman extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPeminjaman
     */
    PeminjamanController peminjamanController;
    public FormPeminjaman() {
        initComponents();
        peminjamanController = new PeminjamanController(this);
        peminjamanController.isiCboAnggota();
        peminjamanController.isiCboBuku();
        
    }

    public JComboBox getCboKodeAnggota() {
        return cboKodeAnggota;
    }

    public void setCboKodeAnggota(JComboBox cboKodeAnggota) {
        this.cboKodeAnggota = cboKodeAnggota;
    }

    public JComboBox getCboKodeBuku() {
        return cboKodeBuku;
    }

    public void setCboKodeBuku(JComboBox cboKodeBuku) {
        this.cboKodeBuku = cboKodeBuku;
    }

    public JTextField getTxtTglKembali() {
        return txtTglKembali;
    }

    public void setTxtTglKembali(JTextField txtTglKembali) {
        this.txtTglKembali = txtTglKembali;
    }

    public JTextField getTxtTglPinjam() {
        return txtTglPinjam;
    }

    public void setTxtTglPinjam(JTextField txtTglPinjam) {
        this.txtTglPinjam = txtTglPinjam;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboKodeAnggota = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboKodeBuku = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtTglPinjam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTglKembali = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Peminjaman");
        setToolTipText("");
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 14);

        cboKodeAnggota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboKodeAnggota);
        cboKodeAnggota.setBounds(100, 10, 280, 20);

        jLabel2.setText("Kode Buku");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 80, 14);

        cboKodeBuku.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cboKodeBuku);
        cboKodeBuku.setBounds(100, 40, 280, 20);

        jLabel3.setText("Tgl Kembali");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 80, 14);

        txtTglPinjam.setText("jTextField1");
        getContentPane().add(txtTglPinjam);
        txtTglPinjam.setBounds(100, 70, 59, 20);

        jLabel4.setText("Tgl Pinjam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 70, 80, 14);

        txtTglKembali.setText("jTextField2");
        getContentPane().add(txtTglKembali);
        txtTglKembali.setBounds(100, 100, 59, 20);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(10, 130, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 162, 370, 210);

        setBounds(0, 0, 405, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JComboBox cboKodeAnggota;
    private javax.swing.JComboBox cboKodeBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtTglKembali;
    private javax.swing.JTextField txtTglPinjam;
    // End of variables declaration//GEN-END:variables
}